name: rick_and_morty
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-422.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_theme_switcher:
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.2
  http:
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  flutter_staggered_grid_view:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/